PRJ666_G7-Project/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PRJ666_G7_Project.Data;
using PRJ666_G7_Project.Models;

namespace PRJ666_G7_Project.Controllers
{
    [Authorize]
    public class EmployeesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        Manager m = new Manager();

        // GET: Employees
        public ActionResult Index()
        {
            ViewBag.UserAuthLevel = m.EmpGetByUserName(m.User.Name).AuthLevel;
            return View(m.EmpGetAll());
        }

        // GET: Employees/username/Schedule
        [Route("Employees/{username}/Schedule")]
        public ActionResult Schedule(string userName)
        {
            ViewBag.UserAuthLevel = m.EmpGetByUserName(m.User.Name).AuthLevel;

            var sunday = DateTime.Today.AddDays(-(int)DateTime.Today.DayOfWeek + (int)DayOfWeek.Sunday);

            var schedule = m.GetEmployeeScheduleByUserNameWithShift(userName);
            schedule.ShiftList = new SelectList(m.ShiftGetByEmployeeUserName(userName), "Id", "ShiftStart");

            schedule.ShiftsWeekly = new List<EmployeeShiftsWeekly>();
            for (int i = 0; i < 7; i++)
            {
                EmployeeShiftsWeekly sd = new EmployeeShiftsWeekly();
                var day = sunday.AddDays(i);
                sd.ShiftsDate = day;
                List<Shift> shiftsDaily = new List<Shift>();
                foreach (var shift in schedule.Shifts)
                {
                    if (shift.ShiftStart.Date == day.Date)
                    {
                        shiftsDaily.Add(shift);
                    }
                }
                sd.ShiftsDaily = shiftsDaily;
                schedule.ShiftsWeekly.Add(sd);
            }

            return View(schedule);
        }

        [Route("Employees/{username}/tasklist")]
        public ActionResult _TaskListEdit(string userName)
        {
            TaskIndexEditFormViewModel viewModel = new TaskIndexEditFormViewModel();
            viewModel.TaskList = db.Tasks.Include("Employee").Where(x => x.Employee.UserName == userName).ToList().OrderBy(x => x.Deadline);

            return PartialView(viewModel);
        }

        // POST: Employees/{username}/tasklist
        [Route("Employees/{username}/tasklist")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult _TaskListEdit(string username, TaskIndexEditViewModel tasks)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Schedule", new { username = username });
            }

            IEnumerable<Task> taskList = tasks.TaskList;


            foreach(var task in taskList)
            {
                foreach(var taskId in tasks.TaskIds)
                {
                    task.Complete = false;
                    if (task.Id == taskId)
                    {
                        task.Complete = true;
                    }
                }
            }

            var editedItem = m.EmployeeTasksEdit(taskList, username);

            return RedirectToAction("Schedule", new { username = editedItem.UserName });
        }

        // GET: Employees/{username}?shiftId={shiftId}&inOut={inOut}
        /*[Route("Employees/{username}/{shiftId}/{inOut}")]
        public ActionResult ClockInOut(string username, int shiftId, bool inOut)
        {
            if (!ModelState.IsValid) 
            {
                return RedirectToAction("Schedule", new { username = username });
            }

            m.ShiftClockInOut(m.ShiftGetByIdWithDetail(shiftId), inOut);

            return RedirectToAction("Schedule", new { username = username, shiftId = shiftId });
        }*/
    }
}

PRJ666_G7-Project/Controllers/TasksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PRJ666_G7_Project.Data;
using PRJ666_G7_Project.Models;

namespace PRJ666_G7_Project.Controllers
{
    [Authorize]
    public class TasksController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private Manager m = new Manager();
        // GET: Tasks
        [Authorize(Roles = "Manager,Administrator,Super Admin")]
        public ActionResult Index()
        {
            TaskIndexViewModel viewModel = new TaskIndexViewModel();
            viewModel.TaskList = db.Tasks.Include("Employee").ToList().OrderBy(x=> x.Deadline);

            List<EmployeeBaseViewModel> emplList = new List<EmployeeBaseViewModel>();
            emplList.Add(new EmployeeBaseViewModel() { FullName = "Not Selected", UserName="" });
            emplList.AddRange(m.EmpGetAll());
            viewModel.EmployeeList = emplList;

            return View(viewModel);
        }

        // GET: Tasks/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Task task = db.Tasks.Find(id);
            if (task == null)
            {
                return HttpNotFound();
            }
            return View(task);
        }

        // GET: Tasks/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Tasks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create( TaskAddViewModel newItem)
        {
            // Validate the input
            if (!ModelState.IsValid)
            {
                return View(newItem);
            }

            // Process the input
            var addedItem = m.TaskAdd(newItem);

            if (addedItem == null)
            {
                return View(addedItem);
            }
            else
            {
                return RedirectToAction("Index");
            }

            //if (ModelState.IsValid)
            //{
             //db.Tasks.Add(task);
            //    db.SaveChanges();
            //    return RedirectToAction("Index");
            //}

            //return View(task);
        }

        // GET: Tasks/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Task task = db.Tasks.Find(id);
            if (task == null)
            {
                return HttpNotFound();
            }
            return View(task);
        }

        // POST: Tasks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(TaskEditViewModel updatedItem)
        {
            // Validate the input
            if (!ModelState.IsValid)
            {
                return View(updatedItem);
            }

            // Process the input
            if (updatedItem.CompleteChbx == "on")
            {
                updatedItem.Complete = true;
            }
            else
            {
                updatedItem.Complete = false;
            }

            var addedItem = m.TaskEdit(updatedItem);

            if (addedItem == null)
            {
                return View(updatedItem);
            }
            else
            {
                return RedirectToAction("Index");
            }
            //if (ModelState.IsValid)
            //{
            //    db.Entry(task).State = EntityState.Modified;
            //    db.SaveChanges();
            //    return RedirectToAction("Index");
            //}
            //return View(task);
        }

        // GET: Tasks/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Task task = db.Tasks.Find(id);
            if (task == null)
            {
                return HttpNotFound();
            }
            return View(task);
        }

        // POST: Tasks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Task task = db.Tasks.Find(id);
            db.Tasks.Remove(task);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PRJ666_G7-Project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <!-- Do not modify the meta properties below -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="author" content="PRJ666_G7_Project" />
    <meta name="application-name" content="2227-70e7829b-d30d-42f3-9587-e1b2964b69d6" />

    <title>@ViewBag.Title - PRJ666_G7-Project</title>

    @Styles.Render("~/Content/css")
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/css/bootstrap-datetimepicker.min.css" />
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.13.0/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/js/bootstrap-datetimepicker.min.js"></script>
    @{
        var userAccount = new PRJ666_G7_Project.Controllers.RequestUser(User as System.Security.Claims.ClaimsPrincipal);
        var UserAuthLevel = 0;
    }
</head>
<body>
    <div name= "MainHeader" class="navbar navbar-inverse navbar-fixed-top mainheader">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("WSMT", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navigationText">

                    <li>@Html.ActionLink("My Schedule", "Schedule", "Employees", new { username = User.Identity.Name }, null)</li>
                    @if (!User.IsInRole("Employee"))
                    {
                        <li>@Html.ActionLink("Manage Schedule", "Index", "Shifts")</li>
                    }
                    @if (!User.IsInRole("Employee"))
                    {
                        <li>@Html.ActionLink("Manage Tasks", "Index", "Tasks")</li>
                    }
                    <li>@Html.ActionLink("My Organization", "Index", "Employees")</li>
                    <li>@Html.ActionLink("Notifications", "Index", "Notifications", new { username = User.Identity.Name }, null)</li>
                    </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; Group 7, PRJ666</p>
        </footer>
    </div>

    
    @RenderSection("scripts", required: false)
</body>
</html>